### ISSUE TITLE
Scrolling viewport buggy/no fluid movement on Win8.1 Touch & Firefox 26

### ISSUE THREAD

**Issue by scotta98** [blueimp/Gallery#101]
Scrolling through images using swipe on Windows 8.1 TouchSmart Desktop & Firefox 26 is not fluid. Sometimes images are cut in half where old and new are both out of the main frame. Other times you are unable to swipe at all. There seems to be no response to touch of the actual image. Touch outside of the border of the actual image seems to have desired effect.

**Comment by blueimp** [comment]
Any of the previous posters, are the issues still reproducible on IE11 or latest Firefox on Windows touch devices?

**Comment by blueimp** [comment]
Closing this as obsolete. Feel free to reopen if this should still be an issue.
