### ISSUE TITLE
I hope that this project can add a picture zoom function

### ISSUE THREAD

**Issue by janryWang** [blueimp/Gallery#121]
I hope that this project can add a picture zoom function,thanks!

**Comment by flyingL123** [comment]
Has this changed at all? Is there any chance being able to pinch zoom on images? Has anyone created a fork that has this ability?

**Comment by blueimp** [comment]
Nobody has sent a pull request for this unfortunately and I'm not aware of a fork with this ability, although it might well exist.

**Comment by blueimp** [comment]
The latest version `blueimp-gallery@2.44.0` enables the browser default pinch-to-zoom functionality.
