### ISSUE TITLE
data-href is not retrieved with option urlProperty unspecified (default === 'href')

### ISSUE THREAD

**Issue by Lisa-Williams** [blueimp/Gallery#147]
Before opening this issue, I've searched, and found this similar issue. But I disagree. I think that this is a bug. : https://github.com/blueimp/Gallery/issues/112

I wanted to change all my URLs from `href` to `data-href`. And it failed.
To simplify things and exclude my own code and markup, I tried the `Lightbox setup` of the `README.md` (The very first one), with some of my own images and thumbs, and the large photos showed up in the lightbox on click. (This is with `href`s.)

I then changed the `href`s in the list to `data-href` and the large photos failed to show in the lightbox. (red circle with slash through it).

The `urlProperrty` option is not specified so it has to be the default href.
According to the `README.md`, this should pick up URLs specified in either `href` or `data-href`.

I debugged this and it appears that your check after the attempt to retrieve the image URL from the `href` is wrong.
This one https://github.com/blueimp/Gallery/blob/master/js/blueimp-gallery.js#L1174:
`if (prop === undefined) {`.

It's in this snippet of `blueimp-gallery.js`:

``` JavaScript
        getItemProperty: function (obj, property) {
            var prop = obj[property];
            if (prop === undefined) {
                prop = this.getDataProperty(obj, property);
                if (prop === undefined) {
                    prop = this.getNestedProperty(obj, property);
                }
            }
            return prop;
        },
```

With the debugger stopped on a breakpoint on line (1173) with `var prop = obj[property];`:  `prop` has a `typeof` `undefined`.

After execution of line 1173, with the debugger stoppped on line 1174, the value of `prop` is now `empty string` (`""`) because Chrome stores a missing `href` as an empty string.

So the `if` statement will always fail, because it will never have a `typeof` `undefined`. And therefore there is never an attempt made to retrieve the URL from `data-href`.

You can see it in the screenshot :

![blueimp-data-href-wrong-check](https://cloud.githubusercontent.com/assets/2570736/3153396/e240a964-ea9a-11e3-8ced-6e3bd840635b.png)

**Comment by blueimp** [comment]
Closing as resolved.
