### ISSUE TITLE
Patch that greatly lowers the memory consumption (tested on ipad)

### ISSUE THREAD

**Issue by thehappycoder** [blueimp/Gallery#165]
After some trial and error with iOS simulator and Instruments (and on real ipad in the end) I was able to find out how to lower the gallery memory consumption on load.

Also this patch seems to be solving this issue:
https://github.com/blueimp/Bootstrap-Image-Gallery/issues/147

The patch https://gist.github.com/thehappycoder/72cde85fbfec9643fa7d
It's not perfect so it may break something I didn't foresee.

If you set memoryOptimizations=false and preloadRange=1 it's almost the same as memoryOptimizations=true with any preloadRange with one exception that the latter frees memory much quicker.

**Comment by blueimp** [comment]
Sorry for reviving a years old issue @thehappycoder.
Is the memory pressure still an issue on the current version with current devices?
Is the preloadRange an acceptable solution?
Or would you be willing to create a clean pull request? :)

**Comment by thehappycoder** [comment]
@blueimp Unfortunately, I don't remember this issue anymore. But it's good to realise I contributed a bit.

**Comment by blueimp** [comment]
No worries and thanks for the reply. ☺️
