### ISSUE TITLE
Overlapping thumbnails on load

### ISSUE THREAD

**Issue by ariia-git** [blueimp/Gallery#234]
When loading the web page with gallery, the images of the gallery overlap on occasion. 

Is there a way to resolve this?

**Comment by blueimp** [comment]
Hi @ariia-git,
unfortunately, this report doesn't provide enough information for me to reproduce the issue.

Could you provide details on:
* the browser used
* steps to reproduce the problem
* potentially screenshots or a video?

**Comment by blueimp** [comment]
Closing as non-reproducible.
