### ISSUE TITLE
Combine slider and lightbox?

### ISSUE THREAD

**Issue by ursbraem** [blueimp/Gallery#237]
The title says it: does blueimp support an integrated combination of slider and lightbox? So instead of the thumbnails for the lightbox, there is a clickable slider?

**Comment by blueimp** [comment]
It does not out of the box, but you could potentially add support by creating your own content factory as described in the documentation:
https://github.com/blueimp/Gallery#additional-content-types

**Comment by blueimp** [comment]
Closing this, as I don't have plans to implement such a feature.
