### ISSUE TITLE
Scrollbar stays hidden after routing out of the gallery

### ISSUE THREAD

**Issue by mickgr** [blueimp/Gallery#239]
When keeping hidePageScrollbars option with default true,
When opening the Gallery, overflow:hidden style is appended to the Body element.
if you then press the back button on the browser, this Gallery close() function is not called and the style is not removed.
This is causing the browser to keep hiding the scroll.

**Comment by blueimp** [comment]
Resolved via https://github.com/blueimp/Gallery/pull/240.
