### ISSUE TITLE
Is it possible to use videos without a poster?

### ISSUE THREAD

**Issue by JesseHines0** [blueimp/Gallery#245]
I am trying to create a video gallery, but I don't have poster images available for each video. Is it there a way in lightbox mode to make the gallery either use the first video frame as the poster, or not show the poster at all and just directly show the video player?

**Comment by blueimp** [comment]
Thanks for your suggestion @JesseHines0.

The video Gallery now displays the active video element if no poster is provided and also if the video is paused.

Please note that by default, videos are not preloaded, so will only show an empty screen, however you can change the preloading behavior:
https://github.com/blueimp/Gallery#video-preloading

**Comment by JesseHines0** [comment]
@blueimp That will work perfectly. Thanks!
