### ISSUE TITLE
blueimp-gallery.css vs blueimp-gallery.min.css 

### ISSUE THREAD

**Issue by githubcek** [blueimp/Gallery#246]
If I compare blueimp-gallery.min.css and blueimp-gallery.css:
blueimp-gallery.css doesn't have ".indicator" part.

(v3.0.0)

**Comment by blueimp** [comment]
I admit that this is misleading, but the minified versions also bundle all the individual components together.

You can see the related build commands here:
https://github.com/blueimp/Gallery/blob/80dbf50da012b0f697ec5ba623f55b2d43fab019/package.json#L80-L82

Unfortunately changing these filenames to something more clear (e.g. `blueimp-gallery.all.min.css`) would potentially break existing workflows, so I prefer to keep it that way.

**Comment by githubcek** [comment]
Thank you for explaining.
