### ISSUE TITLE
DevTool error

### ISSUE THREAD

**Issue by ThibaultMagy** [blueimp/Gallery#247]
Hi, I sometimes get this warning in console when I'm redirected to a page using bluimp-gallery's carousel

DevTools failed to load SourceMap: Could not load content for /root/path/blueimp-gallery.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE.

Does someone knows where it could come from ?

**Comment by blueimp** [comment]
Hi @ThibaultMagy,

you probably want to learn about [source maps](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map).

As soon as you open Dev Tools and the JavaScript source code references a source map, they will try to download it.
The minified files of the Gallery contain a source map reference here:
https://github.com/blueimp/Gallery/blob/80dbf50da012b0f697ec5ba623f55b2d43fab019/js/blueimp-gallery.min.js#L2

The project also includes the source map file, so all you need to do is copy it to the same location as Gallery JavaScript files:
https://github.com/blueimp/Gallery/blob/master/js/blueimp-gallery.min.js.map

**Comment by blueimp** [comment]
Closing this as resolved, feel free to commend if there should be further questions.

**Comment by Timobakker** [comment]
Wij genieten van een vakantie! Dus het kan even duren voordat u een reactie ontvangt op uw mail.

**Comment by blueimp** [comment]
(deleted the email auto-reply, which was "Wij genieten van een vakantie! Dus het kan even duren voordat u een reactie ontvangt op uw mail.")
