### ISSUE TITLE
Response images

### ISSUE THREAD

**Issue by drMonro** [blueimp/Gallery#248]
Hello. Please, help to understand how work images response?
I made image-link responsive working correct by using data-srcset and data-sizes via a attributes/

But i can't understand how to make responsive img - i'm tried to use tag <picture>, but when full screen linking starting working not correct (forever open first image)

I understand what documentation have article about response. But it don't have example about responsing images in markup..  

```
                 <a
                    href="assets/img/desktop.jpg"

                    data-srcset="assets/img/desktop.jpg 800w,
                                         assets/img/mobile.jpg 500w"

                    data-sizes="(max-width: 767px) 500px, (max-width: 1200px) 800px"
                >
                    <img src="assets/img/example.jpg"/>
                </a> 
```

**Comment by blueimp** [comment]
Hi @drMonro,

the `data-srcset` and `data-sizes` map 1:1 to HTML image properties [srcset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset) and [sizes](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/sizes).

The [README](https://github.com/blueimp/Gallery/blob/master/README.md#responsive-images) also links to documentation about [responsive images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images).

Hope that helps!

**Comment by blueimp** [comment]
Closing this as resolved.
