### ISSUE TITLE
Option to deactivate or reactivate keyboard navigation

### ISSUE THREAD

**Issue by calaoa** [blueimp/Gallery#249]
Hi everyone, Hi blueimp,

While implementing a [Vue wrapper for blueimp Gallery](https://framagit.org/babouk/vue-blueimp-gallery) with ability to edit an image caption directly from the gallery, I have the following question: would there be a way to temporarily deactivate the keyboard shortcuts (typically while editing such a caption, we don't want the arrows to fire a slide change but rather navigate the edited text), or would this require a change in the code? What's your take on this?

Demo : https://codesandbox.io/s/vue-blueimp-gallery-y8b77

Cheers 👏

**Comment by blueimp** [comment]
Hi @calaoa,

while this is not an official API, you do have access to the `options` property on the `Gallery` object, which allows you to change the keyboard related options during runtime, e.g.:

```js
var gallery = blueimp.Gallery(links)

gallery.options.toggleControlsOnEnter = false
gallery.options.toggleSlideshowOnSpace = false
gallery.options.enableKeyboardNavigation = false
gallery.options.closeOnEscape = false
```

This allows you to temporarily disable and reenable the keyboard shortcuts.

**Comment by calaoa** [comment]
Thank you @blueimp it works great indeed, closing this issue then!
