### ISSUE TITLE
Navigation controls incorrectly positionned on Firefox

### ISSUE THREAD

**Issue by calaoa** [blueimp/Gallery#250]
Hi everyone, While on Chromium the default prev/next controls are correctly aligned vertically, it seems they are not in Firefox: see example below with Firefox 77.0.1. Tiinkering with the line-height property seems to improve the layout, not sure if it's the best option though?

![blueimp-gallery](https://user-images.githubusercontent.com/59505767/86940542-40104880-c143-11ea-9e1a-74076d5bafc4.jpg)

**Comment by blueimp** [comment]
Thanks for the report @calaoa.
I've released version `3.1.0` which fixes this issues by making use of background-images instead.
