### ISSUE TITLE
I have an issue if the gallery is opend on the mobile

### ISSUE THREAD

**Issue by MasterMindNET** [blueimp/Gallery#252]
Gallery ver: 3.2.*
Tested in chrome canary 86, chrome 84. and chrome 83.

Steps to reproduce:
1. go the page
2. open my slide bar
3.  wait a second

Actual result: the error appears instead of showing the image.
Expected results: the image is shown and can be slided.

blueimp-gallery.js:1022 Uncaught TypeError: Cannot read property 'removeAttribute' of undefined
    at i.updateActiveSlide (blueimp-gallery.js:1022)
    at i.handleSlide (blueimp-gallery.js:1029)
    at i.handleSlide (blueimp-gallery-indicator.js:135)
    at i.handleSlide (blueimp-gallery-video.js:53)
    at i.onslide (blueimp-gallery.js:1038)
    at i.slide (blueimp-gallery.js:391)
    at blueimp-gallery.js:427

![image](https://user-images.githubusercontent.com/22347676/88946661-312b3a80-d298-11ea-8e1d-d2bf9e55db91.png)

my view:
![image](https://user-images.githubusercontent.com/22347676/88946782-55871700-d298-11ea-9d0e-87735d14f101.png)

Please help me out, what could I did wrong?

**Comment by blueimp** [comment]
Hello @MasterMindNET,

if you cannot reproduce the issue on the [demo](https://blueimp.github.io/Gallery/), it's likely a configuration error.
Maybe you tried to move to a slide index that doesn't exist?

**Comment by blueimp** [comment]
@MasterMindNET is this still an issue or could you solve it in your integration code?

**Comment by MasterMindNET** [comment]
Yeah, pardon me, please. this issue is somewhere in my the project. The gallery works fine.
 I am closing it. 

Thank you so much for immediate response!
