### ISSUE TITLE
modal stuck after closing gallery using ESC

### ISSUE THREAD

**Issue by Maransatto** [blueimp/Gallery#257]
Hi, 

I have a bootstrap modal and inside it a gallery.
The issue I'm facing is when I hit the keyboard button "Esc" to close the gallery.
When I do this, the gallery is close and so the bootstrap modal.

After that, when I open the modal again, it becomes completely static.

Is there any way to prevent the gallery of being closed when hitting esc button? or maybe trying to fix this sync issue.

Note: I'm using it with angular.

**Comment by Maransatto** [comment]
I've just found the solution.
Instead of preventing the gallery to close on exit, I prevent the modal adding the following attributes:
`data-backdrop="static" data-keyboard="false"`

https://solidlystated.com/design/bootstrap-modal-disable-closing-with-esc-key-or-mouse/

**Comment by blueimp** [comment]
Closing as solved.
