### ISSUE TITLE
Display iframe as slide content instead of image

### ISSUE THREAD

**Issue by ManuelHaas** [blueimp/Gallery#264]
Hi Sebastian,

thank you for your great libraries (gallery, file-upload, canvas-to-blob etc.)!
I would like to extend the gallery to display pdf. I have already developed a working solution using pdf.js. This can be included using iframe. I'm just looking for a way how to display my iframe as slide content (instead of the image) when the pdf is clicked and the gallery is opened. Do you have a tip for me how to implement this?

Many thanks!

**Comment by blueimp** [comment]
Hi @ManuelHaas,
yes, there is a way to display any kind of content via [additional content types](https://github.com/blueimp/Gallery#additional-content-types).
You could implement an `applicationFactory` that checks the `obj` argument property `obj.type` for `application/pdf` and returns an element that will display the PDF (e.g. using PDF.js).

**Comment by ManuelHaas** [comment]
@blueimp Thank you so much for your explanations. You saved my day!
