### ISSUE TITLE
using WebPack

### ISSUE THREAD

**Issue by adampatterson** [blueimp/Gallery#265]
I loaded the script through NPM and am importing blueimp like so `import blueimp, from 'blueimp-gallery'`

My config looks like this.

```javascript
    document.getElementById('gallery').onclick = function (event) {
        event = event || window.event
        var target = event.target || event.srcElement,
            link = target.src ? target.parentNode : target,
            options = {
                index: link,
                event: event
            },
            links = this.getElementsByTagName('a')
        blueimp(links, options)
    }
```

I am not sure how to get the indicators to work. The examples show loading a separate file for the indicators. 

I see `indicatorOptions` but don't see how they apply to the options.

If it's possible can I get an example? Otherwise, I will probably use a CDN for the files as I don't want to upload the NPM folder.

Thanks for the help!

**Comment by adampatterson** [comment]
I ended up loading the files individually.

**Comment by sebastian-marinescu** [comment]
Hi @adampatterson, 

I also import it individually: 
```
import Gallery from 'blueimp-gallery';
import 'blueimp-gallery/js/blueimp-gallery-indicator';
```

And inside your options-object, you can specify more options: 
```
            indicatorContainer: 'ol',
            thumbnailProperty: 'thumbnail',
            thumbnailIndicators: true,
```

I think this issue can be closed 👍
