### ISSUE TITLE
Typo bug? 

### ISSUE THREAD

**Issue by arturmamedov** [blueimp/Gallery#273]
https://github.com/blueimp/Gallery/blob/master/js/blueimp-gallery.js#L286

**Comment by sebastian-marinescu** [comment]
Hi @arturmamedov, I don't think so: 

![image](https://user-images.githubusercontent.com/3798871/235447981-05769b16-f497-4577-ac94-0d303faee76a.png)

![image](https://user-images.githubusercontent.com/3798871/235447853-daa76fbc-872b-4e49-a416-b0dcc3855083.png)

![image](https://user-images.githubusercontent.com/3798871/235447863-a6e356b5-476d-4d8b-af2f-601544e95459.png)

Seems hackery, but legit 😄 
I think you can close this 👍
